import "@styles/_aula-03.scss"
function Hexagon() {
    return ( 
        <div className="container">
            <div className="row">
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
            </div>
            <div className="row">
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
            </div>
            <div className="row">
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
            </div>
            <div className="row">
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
            </div>
            <div className="row">
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
            </div>
            <div className="row">
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
            </div>
            <div className="row">
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
            </div>
            <div className="row">
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
            </div>
            <div className="row">
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
            </div>
            <div className="row">
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
                <div className="hexagon"></div>
            </div>
           
        </div>
     )
}

export { Hexagon as HoveredHexagonEffect }